import { priceRarity } from "./case-mechanics";
import type { Food } from "./foods";

export const pubFoods: Food[] = [
  {
    name: "Đậu tẩm hành",
    sub: "Đậu rán phủ hành lá • Một đĩa",
    price: 60,
    image: 400,
    rarity: priceRarity(60),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Tóp mỡ xào dưa",
    sub: "Tóp mỡ & dưa cải chua • Một đĩa",
    price: 120,
    image: 401,
    rarity: priceRarity(120),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Dưa chuột",
    sub: "Dưa chuột tươi thái miếng • Một đĩa",
    price: 20,
    image: 402,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Lạc rang",
    sub: "Lạc rang giòn • Một đĩa nhỏ",
    price: 20,
    image: 403,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nem chua rán",
    sub: "Nem rán giòn • Phần 5 chiếc",
    price: 40,
    image: 404,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chân gà sả tắc",
    sub: "Chân gà, sả & tắc • Một phần",
    price: 80,
    image: 405,
    rarity: priceRarity(80),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ngô chiên",
    sub: "Ngô ngọt chiên giòn • Một đĩa",
    price: 45,
    image: 406,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Khoai tây chiên",
    sub: "Khoai tây chiên giòn • Một đĩa",
    price: 45,
    image: 407,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Mực khô nướng xé",
    sub: "Mực khô nướng xé sợi • Một phần",
    price: 120,
    image: 408,
    rarity: priceRarity(120),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Lòng xào dưa",
    sub: "Lòng heo & dưa cải chua • Một đĩa",
    price: 150,
    image: 409,
    rarity: priceRarity(150),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sụn gà rang muối",
    sub: "Sụn gà giòn & muối rang • Một đĩa",
    price: 130,
    image: 410,
    rarity: priceRarity(130),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Gỏi xoài khô bò",
    sub: "Xoài xanh, khô bò & rau thơm • Một đĩa",
    price: 40,
    image: 411,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Má đào cháy tỏi",
    sub: "Thịt má heo áp chảo với tỏi • Một phần",
    price: 145,
    image: 412,
    rarity: priceRarity(145),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Gà chiên mắm",
    sub: "Gà chiên áo nước mắm tỏi • Một phần",
    price: 130,
    image: 413,
    rarity: priceRarity(130),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sụn gà chiên mắm",
    sub: "Sụn gà giòn sốt nước mắm • Một phần",
    price: 130,
    image: 414,
    rarity: priceRarity(130),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chân gà sốt Thái",
    sub: "Chân gà trộn sốt chua cay • Một phần",
    price: 90,
    image: 415,
    rarity: priceRarity(90),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Lòng gà xào mướp",
    sub: "Lòng gà xào cùng mướp hương • Một phần",
    price: 120,
    image: 416,
    rarity: priceRarity(120),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Dạ dày cháy tỏi",
    sub: "Dạ dày heo giòn xóc tỏi • Một phần",
    price: 180,
    image: 417,
    rarity: priceRarity(180),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Dồi sụn nướng",
    sub: "Dồi heo có sụn nướng thơm • Một phần",
    price: 120,
    image: 418,
    rarity: priceRarity(120),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Tai heo bóp thính",
    sub: "Tai heo thái mỏng, thính & rau thơm • Một phần",
    price: 100,
    image: 419,
    rarity: priceRarity(100),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ba chỉ rang riềng",
    sub: "Ba chỉ heo rang thơm riềng • Một phần",
    price: 130,
    image: 420,
    rarity: priceRarity(130),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ba chỉ nướng riềng mẻ",
    sub: "Ba chỉ heo ướp riềng mẻ nướng • Một phần",
    price: 150,
    image: 421,
    rarity: priceRarity(150),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bò lúc lắc",
    sub: "Bò áp chảo cùng hành & ớt chuông • Một phần",
    price: 160,
    image: 422,
    rarity: priceRarity(160),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Gân bò cháy tỏi",
    sub: "Gân bò giòn xóc tỏi • Một phần",
    price: 130,
    image: 423,
    rarity: priceRarity(130),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bò xào cần",
    sub: "Thịt bò xào cùng rau cần • Một phần",
    price: 150,
    image: 424,
    rarity: priceRarity(150),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ếch xào sả ớt",
    sub: "Thịt ếch xào sả & ớt • Một phần",
    price: 130,
    image: 425,
    rarity: priceRarity(130),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ếch chiên bơ",
    sub: "Thịt ếch chiên giòn xóc bơ • Một phần",
    price: 135,
    image: 426,
    rarity: priceRarity(135),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Vịt cháy tỏi",
    sub: "Thịt vịt áp chảo cùng tỏi • Một phần",
    price: 130,
    image: 427,
    rarity: priceRarity(130),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Lưỡi vịt rang muối",
    sub: "Lưỡi vịt giòn xóc muối rang • Một phần",
    price: 125,
    image: 428,
    rarity: priceRarity(125),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chim câu quay",
    sub: "Chim bồ câu quay vàng • Một con",
    price: 170,
    image: 429,
    rarity: priceRarity(170),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Rau muống xào tỏi",
    sub: "Rau muống xanh giòn xào tỏi • Một đĩa",
    price: 50,
    image: 430,
    rarity: priceRarity(50),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ngọn su su xào tỏi",
    sub: "Ngọn su su non xào tỏi • Một đĩa",
    price: 65,
    image: 431,
    rarity: priceRarity(65),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Rau củ luộc chấm kho quẹt",
    sub: "Rau củ & kho quẹt tôm khô tóp mỡ • Một đĩa",
    price: 80,
    image: 432,
    rarity: priceRarity(80),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Đậu hũ chiên sả",
    sub: "Đậu hũ chiên giòn xóc sả • Một đĩa",
    price: 50,
    image: 433,
    rarity: priceRarity(50),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cà tím nướng mỡ hành",
    sub: "Cà tím nướng phủ mỡ hành • Một đĩa",
    price: 50,
    image: 434,
    rarity: priceRarity(50),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cải thìa xào nấm",
    sub: "Cải thìa xanh xào cùng nấm • Một đĩa",
    price: 80,
    image: 435,
    rarity: priceRarity(80),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Đậu bắp nướng",
    sub: "Đậu bắp nướng xém cạnh • Một đĩa",
    price: 50,
    image: 436,
    rarity: priceRarity(50),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nộm xoài tép khô",
    sub: "Xoài xanh, tép khô & rau thơm • Một đĩa",
    price: 80,
    image: 437,
    rarity: priceRarity(80),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nghêu hấp sả",
    sub: "Nghêu hấp thơm sả • Một phần",
    price: 70,
    image: 438,
    rarity: priceRarity(70),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Hàu sữa nướng mỡ hành",
    sub: "Hàu nướng phủ mỡ hành • Phần 5 con",
    price: 70,
    image: 439,
    rarity: priceRarity(70),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ốc móng tay xào rau muống",
    sub: "Ốc móng tay xào rau muống & tỏi • Một phần",
    price: 75,
    image: 440,
    rarity: priceRarity(75),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ốc len xào dừa",
    sub: "Ốc len nấu nước cốt dừa • Một phần",
    price: 110,
    image: 441,
    rarity: priceRarity(110),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sò huyết xào me",
    sub: "Sò huyết xào sốt me chua ngọt • Một phần",
    price: 110,
    image: 442,
    rarity: priceRarity(110),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sò điệp nướng mỡ hành",
    sub: "Sò điệp nướng phủ mỡ hành • Một phần",
    price: 70,
    image: 443,
    rarity: priceRarity(70),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Tôm nướng muối ớt",
    sub: "Tôm nướng với muối & ớt • Một phần",
    price: 115,
    image: 444,
    rarity: priceRarity(115),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Mực hấp gừng sả",
    sub: "Mực hấp gừng & sả • Một phần",
    price: 150,
    image: 445,
    rarity: priceRarity(150),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Mực trứng chiên lá lốt",
    sub: "Mực trứng chiên cùng lá lốt • Một phần",
    price: 150,
    image: 446,
    rarity: priceRarity(150),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Râu mực chiên mắm",
    sub: "Râu mực chiên sốt nước mắm • Một phần",
    price: 140,
    image: 447,
    rarity: priceRarity(140),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
];
