import { priceRarity } from "./case-mechanics";
import type { Food } from "./foods";

export const snackFoods: Food[] = [
  {
    name: "Bánh tráng trộn",
    sub: "Bánh tráng, khô bò & trứng cút • Một phần",
    price: 30,
    image: 156,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cá viên chiên",
    sub: "Cá viên chiên kèm tương • Một phần",
    price: 30,
    image: 157,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nem chua rán",
    sub: "Nem rán giòn • Phần 5 chiếc",
    price: 40,
    image: 158,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Khoai tây chiên",
    sub: "Khoai tây chiên giòn • Một phần",
    price: 30,
    image: 159,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Takoyaki",
    sub: "Bánh bạch tuộc • Phần 6 viên",
    price: 35,
    image: 160,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh flan",
    sub: "Caramen trứng sữa • Một bánh",
    price: 15,
    image: 161,
    rarity: priceRarity(15),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè đậu đen",
    sub: "Đậu đen & nước cốt dừa • Một chén",
    price: 30,
    image: 162,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh trứng nướng",
    sub: "Vỏ bánh giòn & nhân trứng sữa • Một bánh",
    price: 25,
    image: 163,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh cheesecake",
    sub: "Bánh phô mai & quả mọng • Một lát",
    price: 80,
    image: 164,
    rarity: priceRarity(80),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trái cây dầm",
    sub: "Trái cây tươi & sữa chua • Một phần",
    price: 40,
    image: 165,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa chua nếp cẩm",
    sub: "Sữa chua & nếp cẩm • Một hũ",
    price: 20,
    image: 166,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Hạt điều rang",
    sub: "Hạt điều rang giòn • Phần nhỏ 60 g",
    price: 40,
    image: 167,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh tráng nướng",
    sub: "Trứng, xúc xích & hành • Một bánh",
    price: 25,
    image: 300,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh tráng cuốn",
    sub: "Bánh tráng, khô bò & trứng cút • Một phần",
    price: 30,
    image: 301,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh tráng bơ",
    sub: "Bánh tráng, sốt bơ & ruốc • Một phần",
    price: 25,
    image: 302,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bột chiên",
    sub: "Bột chiên trứng & đu đủ bào • Một đĩa nhỏ",
    price: 35,
    image: 303,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Há cảo tôm",
    sub: "Há cảo hấp nhân tôm • Phần 5 viên",
    price: 35,
    image: 304,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sủi cảo chiên",
    sub: "Vỏ giòn, nhân thịt • Phần 5 chiếc",
    price: 35,
    image: 305,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh gối",
    sub: "Nhân thịt, miến & mộc nhĩ • Hai bánh",
    price: 30,
    image: 306,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh rán mặn",
    sub: "Vỏ nếp giòn, nhân thịt • Ba bánh",
    price: 25,
    image: 307,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh giò",
    sub: "Bột gạo, thịt băm & mộc nhĩ • Một bánh",
    price: 25,
    image: 308,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh đúc nóng",
    sub: "Bánh đúc mềm, thịt băm & hành phi • Một bát",
    price: 25,
    image: 309,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh bèo",
    sub: "Bánh bèo tôm chấy & mỡ hành • Phần 6 chén",
    price: 35,
    image: 310,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh bột lọc",
    sub: "Bánh bột lọc nhân tôm thịt • Phần 6 chiếc",
    price: 35,
    image: 311,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh nậm",
    sub: "Bột gạo, tôm thịt gói lá • Phần 4 bánh",
    price: 25,
    image: 312,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh khọt",
    sub: "Bánh giòn nhân tôm & rau sống • Phần 6 bánh",
    price: 30,
    image: 313,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bắp xào tôm khô",
    sub: "Bắp, tôm khô & hành lá • Một ly",
    price: 30,
    image: 314,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bắp nướng mỡ hành",
    sub: "Bắp nướng thơm & hành lá • Một trái",
    price: 15,
    image: 315,
    rarity: priceRarity(15),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bắp luộc",
    sub: "Bắp luộc nóng • Một trái",
    price: 12,
    image: 316,
    rarity: priceRarity(12),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Khoai lang nướng",
    sub: "Khoai lang nướng nguyên củ • Một củ",
    price: 20,
    image: 317,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Khoai lang kén",
    sub: "Khoai lang viên chiên giòn • Một phần",
    price: 25,
    image: 318,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Phô mai que",
    sub: "Phô mai tẩm bột chiên • Phần 3 que",
    price: 50,
    image: 319,
    rarity: priceRarity(50),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Xúc xích nướng",
    sub: "Xúc xích nướng kèm tương • Hai cây",
    price: 25,
    image: 320,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chân gà sả tắc",
    sub: "Chân gà ngâm sả, tắc & ớt • Một phần",
    price: 80,
    image: 321,
    rarity: priceRarity(80),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chân gà nướng",
    sub: "Chân gà nướng sa tế • Phần 4 chiếc",
    price: 90,
    image: 322,
    rarity: priceRarity(90),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trứng cút lộn xào me",
    sub: "Trứng cút lộn, sốt me & rau răm • Một phần",
    price: 30,
    image: 323,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ốc luộc",
    sub: "Ốc hấp sả, chấm mắm gừng • Một phần nhỏ",
    price: 40,
    image: 324,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ốc xào dừa",
    sub: "Ốc len xào nước cốt dừa • Một phần nhỏ",
    price: 50,
    image: 325,
    rarity: priceRarity(50),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sò điệp nướng mỡ hành",
    sub: "Sò điệp, hành lá & đậu phộng • Phần 4 con",
    price: 50,
    image: 326,
    rarity: priceRarity(50),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Khô gà lá chanh",
    sub: "Khô gà xé cay nhẹ • Phần nhỏ 50 g",
    price: 30,
    image: 327,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Khô bò sợi",
    sub: "Khô bò xé sợi • Phần nhỏ 50 g",
    price: 45,
    image: 328,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Mực rim me",
    sub: "Mực khô rim chua ngọt • Phần nhỏ 50 g",
    price: 30,
    image: 329,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chuối chiên",
    sub: "Chuối ép chiên giòn • Hai bánh",
    price: 20,
    image: 330,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh cam",
    sub: "Vỏ mè, nhân đậu xanh • Phần 3 bánh",
    price: 25,
    image: 331,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh tiêu",
    sub: "Bánh tiêu phủ mè • Hai bánh",
    price: 20,
    image: 332,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh bò hấp",
    sub: "Bánh bò mềm & nước cốt dừa • Một phần",
    price: 20,
    image: 333,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh bò nướng",
    sub: "Bánh bò lá dứa nướng • Hai lát",
    price: 25,
    image: 334,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh da lợn",
    sub: "Lá dứa, đậu xanh & cốt dừa • Một phần",
    price: 20,
    image: 335,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh khoai mì nướng",
    sub: "Khoai mì & nước cốt dừa • Hai lát",
    price: 25,
    image: 336,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh chuối hấp",
    sub: "Chuối hấp, cốt dừa & mè • Một phần",
    price: 20,
    image: 337,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh su kem",
    sub: "Bánh su nhân kem sữa • Phần 4 bánh",
    price: 25,
    image: 338,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bông lan trứng muối",
    sub: "Bông lan, trứng muối & chà bông • Một hộp nhỏ",
    price: 40,
    image: 339,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè bưởi",
    sub: "Cùi bưởi, đậu xanh & cốt dừa • Một ly",
    price: 25,
    image: 340,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè Thái",
    sub: "Mít, thạch & sữa dừa • Một ly",
    price: 35,
    image: 341,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè ba màu",
    sub: "Đậu đỏ, đậu xanh & thạch lá dứa • Một ly",
    price: 30,
    image: 342,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè đậu xanh",
    sub: "Đậu xanh nấu mềm & cốt dừa • Một chén",
    price: 25,
    image: 343,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè đậu đỏ",
    sub: "Đậu đỏ & nước cốt dừa • Một ly",
    price: 25,
    image: 344,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè trôi nước",
    sub: "Viên nếp nhân đậu xanh & nước gừng • Một chén",
    price: 25,
    image: 345,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè khoai dẻo",
    sub: "Khoai dẻo, thạch & sữa dừa • Một chén",
    price: 30,
    image: 346,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chè sương sa hạt lựu",
    sub: "Thạch, hạt lựu & đậu xanh • Một ly",
    price: 30,
    image: 347,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Tào phớ",
    sub: "Tàu hũ mềm & nước đường gừng • Một chén",
    price: 15,
    image: 348,
    rarity: priceRarity(15),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa chua mít",
    sub: "Sữa chua, mít & thạch • Một chén",
    price: 25,
    image: 349,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Kem dừa",
    sub: "Kem dừa, dừa sợi & đậu phộng • Một phần",
    price: 35,
    image: 350,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Kem xôi",
    sub: "Xôi lá dứa & kem dừa • Một chén",
    price: 30,
    image: 351,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Kem chuối",
    sub: "Chuối, cốt dừa & đậu phộng • Một miếng",
    price: 15,
    image: 352,
    rarity: priceRarity(15),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh đúc lá dứa",
    sub: "Bánh đúc ngọt, cốt dừa & nước đường • Một phần",
    price: 25,
    image: 353,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Đậu phộng rang",
    sub: "Đậu phộng rang muối • Phần nhỏ 50 g",
    price: 15,
    image: 354,
    rarity: priceRarity(15),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Hạt hướng dương",
    sub: "Hạt hướng dương rang • Phần nhỏ 50 g",
    price: 15,
    image: 355,
    rarity: priceRarity(15),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Hạt bí rang",
    sub: "Hạt bí rang giòn • Phần nhỏ 50 g",
    price: 20,
    image: 356,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Hạt dẻ rang",
    sub: "Hạt dẻ rang nóng • Phần nhỏ 100 g",
    price: 25,
    image: 357,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Rong biển sấy",
    sub: "Rong biển sấy giòn vị muối • Một gói nhỏ",
    price: 20,
    image: 358,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Đậu nành rang",
    sub: "Đậu nành rang giòn • Phần nhỏ 50 g",
    price: 15,
    image: 359,
    rarity: priceRarity(15),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Dưa hấu",
    sub: "Dưa hấu tươi cắt miếng • Phần 250 g",
    price: 20,
    image: 360,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Dưa lưới",
    sub: "Dưa lưới tươi cắt miếng • Phần 200 g",
    price: 30,
    image: 361,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Ổi",
    sub: "Ổi tươi cắt miếng • Phần 200 g",
    price: 20,
    image: 362,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Xoài chín",
    sub: "Xoài chín cắt miếng • Phần 200 g",
    price: 25,
    image: 363,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cóc",
    sub: "Cóc tươi gọt vỏ • Phần 200 g",
    price: 20,
    image: 364,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Thơm (dứa)",
    sub: "Thơm tươi cắt miếng, còn gọi là khóm • Phần 200 g",
    price: 30,
    image: 365,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bưởi",
    sub: "Bưởi bóc múi • Phần 200 g",
    price: 30,
    image: 366,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cam",
    sub: "Cam tươi cắt múi • Một trái",
    price: 20,
    image: 367,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Quýt",
    sub: "Quýt bóc vỏ • Phần 2 trái",
    price: 20,
    image: 368,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Thanh long",
    sub: "Thanh long tươi cắt miếng • Phần 200 g",
    price: 20,
    image: 369,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Đu đủ",
    sub: "Đu đủ chín cắt miếng • Phần 200 g",
    price: 35,
    image: 370,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chuối",
    sub: "Chuối chín • Hai trái nhỏ",
    price: 10,
    image: 371,
    rarity: priceRarity(10),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Mít",
    sub: "Mít bóc múi, bỏ hạt • Phần 150 g",
    price: 30,
    image: 372,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sầu riêng",
    sub: "Cơm sầu riêng tách múi • Phần 150 g",
    price: 65,
    image: 373,
    rarity: priceRarity(65),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Măng cụt",
    sub: "Măng cụt tươi • Phần 250 g",
    price: 35,
    image: 374,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Chôm chôm",
    sub: "Chôm chôm tươi • Phần 250 g",
    price: 25,
    image: 375,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nhãn",
    sub: "Nhãn tươi • Phần 250 g",
    price: 25,
    image: 376,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Vải",
    sub: "Vải tươi • Phần 250 g",
    price: 30,
    image: 377,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Mãng cầu ta (na)",
    sub: "Na chín tách miếng • Một trái",
    price: 25,
    image: 378,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sapoche",
    sub: "Hồng xiêm chín cắt miếng • Phần 200 g",
    price: 35,
    image: 379,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Vú sữa",
    sub: "Vú sữa chín • Một trái",
    price: 25,
    image: 380,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nho",
    sub: "Nho tươi • Phần 200 g",
    price: 35,
    image: 381,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Táo",
    sub: "Táo tươi cắt miếng • Một trái",
    price: 25,
    image: 382,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Roi (mận miền Nam)",
    sub: "Roi tươi cắt miếng • Phần 200 g",
    price: 25,
    image: 383,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
];
