import { priceRarity } from "./case-mechanics";
import type { Food } from "./foods";

export const drinkFoods: Food[] = [
  {
    name: "Cà phê đen đá",
    sub: "Cà phê phin & đá • Một ly",
    price: 25,
    image: 132,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cà phê sữa đá",
    sub: "Cà phê phin & sữa đặc • Một ly",
    price: 30,
    image: 133,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bạc xỉu",
    sub: "Nhiều sữa, chút cà phê • Một ly",
    price: 30,
    image: 134,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Latte",
    sub: "Espresso & sữa tươi • Một ly",
    price: 55,
    image: 135,
    rarity: priceRarity(55),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà sữa trân châu",
    sub: "Trà sữa & trân châu bột năng • Một ly",
    price: 35,
    image: 136,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà sữa ô long",
    sub: "Trà ô long & sữa • Một ly",
    price: 35,
    image: 137,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Matcha latte",
    sub: "Trà xanh matcha & sữa • Một ly",
    price: 40,
    image: 138,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà sữa Thái",
    sub: "Trà Thái & sữa đặc • Một ly",
    price: 30,
    image: 139,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà đào cam sả",
    sub: "Trà, đào, cam & sả • Một ly",
    price: 35,
    image: 140,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà vải",
    sub: "Trà & vải • Một ly",
    price: 30,
    image: 141,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà chanh",
    sub: "Trà & chanh tươi • Một ly",
    price: 20,
    image: 142,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà tắc",
    sub: "Trà & tắc tươi • Một ly",
    price: 20,
    image: 143,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước ép cam",
    sub: "Cam ép • Một ly",
    price: 30,
    image: 144,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước ép dưa hấu",
    sub: "Dưa hấu ép • Một ly",
    price: 30,
    image: 145,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước ép dứa",
    sub: "Dứa ép • Một ly",
    price: 30,
    image: 146,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước ép ổi",
    sub: "Ổi ép • Một ly",
    price: 30,
    image: 147,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sinh tố bơ",
    sub: "Bơ xay & sữa • Một ly",
    price: 35,
    image: 148,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sinh tố xoài",
    sub: "Xoài xay & sữa • Một ly",
    price: 35,
    image: 149,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sinh tố dâu",
    sub: "Dâu tây xay & sữa • Một ly",
    price: 40,
    image: 150,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sinh tố chuối",
    sub: "Chuối xay & sữa • Một ly",
    price: 35,
    image: 151,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước dừa",
    sub: "Nước dừa tươi • Một phần",
    price: 25,
    image: 152,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước mía",
    sub: "Mía ép & đá • Một ly",
    price: 20,
    image: 153,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa đậu nành",
    sub: "Đậu nành nấu • Một ly",
    price: 15,
    image: 154,
    rarity: priceRarity(15),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước sâm",
    sub: "Nước thảo mộc thanh mát • Một ly",
    price: 20,
    image: 155,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Espresso",
    sub: "Cà phê espresso • Một ly",
    price: 35,
    image: 500,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Americano",
    sub: "Espresso & nước • Một ly",
    price: 40,
    image: 501,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cappuccino",
    sub: "Espresso & bọt sữa • Một ly",
    price: 55,
    image: 502,
    rarity: priceRarity(55),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cà phê ủ lạnh",
    sub: "Cà phê ủ lạnh • Một ly",
    price: 45,
    image: 503,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cà phê trứng",
    sub: "Cà phê & kem trứng • Một ly",
    price: 40,
    image: 504,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cà phê muối",
    sub: "Cà phê & kem muối • Một ly",
    price: 30,
    image: 505,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cà phê cốt dừa",
    sub: "Cà phê & cốt dừa • Một ly",
    price: 45,
    image: 506,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà sữa trà xanh",
    sub: "Trà xanh & sữa • Một ly",
    price: 35,
    image: 507,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà sữa khoai môn",
    sub: "Khoai môn & trà sữa • Một ly",
    price: 35,
    image: 508,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà sữa lài",
    sub: "Trà lài & sữa • Một ly",
    price: 35,
    image: 509,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Hồng trà",
    sub: "Hồng trà nguyên vị • Một ly",
    price: 20,
    image: 510,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà xanh",
    sub: "Trà xanh nguyên vị • Một ly",
    price: 20,
    image: 511,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà ô long",
    sub: "Trà ô long nguyên vị • Một ly",
    price: 25,
    image: 512,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà nhãn sen",
    sub: "Trà, nhãn & hạt sen • Một ly",
    price: 35,
    image: 513,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà xoài",
    sub: "Trà & xoài • Một ly",
    price: 35,
    image: 514,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Trà mãng cầu",
    sub: "Trà & mãng cầu • Một ly",
    price: 35,
    image: 515,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Hojicha latte",
    sub: "Trà rang hojicha & sữa • Một ly",
    price: 45,
    image: 516,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Matcha latte dâu",
    sub: "Matcha, dâu & sữa • Một ly",
    price: 45,
    image: 517,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cacao sữa",
    sub: "Cacao & sữa • Một ly",
    price: 30,
    image: 518,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Cacao kem muối",
    sub: "Cacao & kem muối • Một ly",
    price: 40,
    image: 519,
    rarity: priceRarity(40),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước ép cà rốt",
    sub: "Cà rốt ép • Một ly",
    price: 30,
    image: 520,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước ép táo",
    sub: "Táo ép • Một ly",
    price: 35,
    image: 521,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước ép bưởi",
    sub: "Bưởi ép • Một ly",
    price: 35,
    image: 522,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước ép cóc",
    sub: "Cóc ép • Một ly",
    price: 30,
    image: 523,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sinh tố mãng cầu",
    sub: "Mãng cầu xay & sữa • Một ly",
    price: 35,
    image: 524,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sinh tố sapoche",
    sub: "Sapoche xay & sữa • Một ly",
    price: 35,
    image: 525,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sinh tố dưa gang",
    sub: "Dưa gang xay & sữa • Một ly",
    price: 30,
    image: 526,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa tươi trân châu đường đen",
    sub: "Sữa tươi & trân châu đường đen • Một ly",
    price: 35,
    image: 527,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa hạt sen mè đen",
    sub: "Hạt sen & mè đen • Một ly",
    price: 25,
    image: 528,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa đậu xanh cốt dừa",
    sub: "Đậu xanh & cốt dừa • Một ly",
    price: 25,
    image: 529,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa chua đá",
    sub: "Sữa chua & đá • Một ly",
    price: 25,
    image: 530,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa chua việt quất",
    sub: "Sữa chua & việt quất • Một ly",
    price: 35,
    image: 531,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sữa chua chanh dây",
    sub: "Sữa chua & chanh dây • Một ly",
    price: 35,
    image: 532,
    rarity: priceRarity(35),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước rau má",
    sub: "Rau má xay lọc • Một ly",
    price: 20,
    image: 533,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Rau má đậu xanh",
    sub: "Rau má & đậu xanh • Một ly",
    price: 25,
    image: 534,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước chanh",
    sub: "Chanh tươi & nước • Một ly",
    price: 20,
    image: 535,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước chanh muối",
    sub: "Chanh muối & nước • Một ly",
    price: 20,
    image: 536,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước mơ",
    sub: "Mơ ngâm & nước • Một ly",
    price: 25,
    image: 537,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước sấu",
    sub: "Sấu ngâm & nước • Một ly",
    price: 25,
    image: 538,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sâm bí đao",
    sub: "Bí đao nấu • Một ly",
    price: 20,
    image: 539,
    rarity: priceRarity(20),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước chanh dây",
    sub: "Chanh dây & nước • Một ly",
    price: 25,
    image: 540,
    rarity: priceRarity(25),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Sô cô la đá xay",
    sub: "Sô cô la xay đá • Một ly",
    price: 45,
    image: 541,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Bánh quy kem đá xay",
    sub: "Bánh quy & kem xay đá • Một ly",
    price: 45,
    image: 542,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Matcha đá xay",
    sub: "Matcha & sữa xay đá • Một ly",
    price: 45,
    image: 543,
    rarity: priceRarity(45),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Soda chanh",
    sub: "Soda & chanh • Một ly",
    price: 30,
    image: 544,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Soda dâu",
    sub: "Soda & dâu • Một ly",
    price: 30,
    image: 545,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Soda việt quất",
    sub: "Soda & việt quất • Một ly",
    price: 30,
    image: 546,
    rarity: priceRarity(30),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
  {
    name: "Nước lọc đóng chai",
    sub: "Nước uống đóng chai • Chai 500 ml",
    price: 10,
    image: 547,
    rarity: priceRarity(10),
    quip: "Một lựa chọn tuyệt vời cho hôm nay!",
  },
];
